### PR TITLE
fixed create duplicate display

### LINKED ISSUE #183: create recipe show duplicate
# Describe the Bug
create recipe show duplicate

# Additional Notes

# Story points to fix
1

*How much 'effort' this feature will take to implement. See the respective section in the [Main Dev Doc](https://github.com/cse110-fa21-group2/cse110-fa21-group2/wiki/Main-Developer-Doc#estimating-work-with-story-points) for more information*

### PR DESCRIPTION
**Pull request by hzhfred**
## Details 
fixed create duplicate display

## New Changes
- fixed create duplicate display

## Linked Issue
Closes #183 

## Screenshots
Please include screenshots of any visual changes to the project (new HTML/CSS)

## Checklist
 If it doesn't apply, just mark as completed
- [x ] I have requested 2+ code reviewers
- [x ] I have reviewed and commented my own code.
- [x ] My code follows the style guidelines of this project.
- [ ] I have added new tests as necessary.
- [ ] All new and existing tests pass successfully.

### CODE REVIEW

File: source/js/main.js [hunk 1]
```diff
@@ -444,6 +444,11 @@ const createRecipeClicked = () => {
   if (currSavedPageSelect === 'List 2') {
     // add card to saved recipe page
     const grid = document.querySelector('.saved-recipes .results-grid');
+    const possibleRepeatCard = grid.querySelectorAll(`.id_${finalObject.id}`);
```
Comment (RainbowPangolin) [inline source/js/main.js:447]: It might be helpful to describe what this line is doing, since the bug description in the linked issue isn't comprehensive.

Comment (hzhfred) [reply source/js/main.js:447]: to sync saved recipe page when user create a recipe, we need to create a card in saved recipe page when creating a recipe. local storage doesn't allow duplicates so if you create two same recipe, storage will keep the latest version. But we didn't check for duplicate in current saved recipe page. If you don't refresh the page right now and create two same recipes. although only the later is saved in storage, you will still see duplicate card under saved recipe page. this line checks and remove display repeat in saved recipe page

**Review by farisashai — APPROVED** [review]
